services:
  eureka-server:
    build:
      context: ./eureka-server
    image: elearn-eureka-server
    container_name: elearn-eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservice-network

  postgres:
    image: postgres:15-alpine
    container_name: postgres_elearn
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - microservice-network

  api-gateway:
    build:
      context: ./api-gateway
    image: elearn-api-gateway
    container_name: elearn-api-gateway
    env_file:
      - .env
    environment:
      SPRING_APPLICATION_NAME: api-gateway
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
    ports:
      - "8080:8080"
    networks:
      - microservice-network

  user-service:
    build:
      context: ./user-service
    image: elearn-user-service
    container_name: elearn-user-service
    env_file:
      - .env
    environment:
      SPRING_APPLICATION_NAME: user-service
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
    ports:
      - "8081:8081"
    networks:
      - microservice-network

  ai-service:
    build:
      context: ./ai-service
    image: ai-service
    container_name: ai-service
    env_file:
      - .env
    environment:
      SPRING_APPLICATION_NAME: ai-service
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
    ports:
      - "8084:8084"
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge
volumes:
  postgres_data: