services:
  eureka-server:
    build:
      context: ./eureka-server
    image: elearn-eureka-server
    container_name: elearn-eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservice-network

  postgres:
    image: postgres:15-alpine
    container_name: postgres_elearn
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - microservice-network

  ollama:
    image: ollama/ollama:latest
    container_name: english_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./docker/ollama/ollama-init.sh:/ollama-init.sh
    entrypoint: [ "/bin/sh", "-c" ]
    command: ["chmod +x /ollama-init.sh && /ollama-init.sh"]
    restart: always
    networks:
      - microservice-network

  api-gateway:
    build:
      context: ./api-gateway
    image: elearn-api-gateway
    container_name: elearn-api-gateway
    env_file:
      - .env
    environment:
      SPRING_APPLICATION_NAME: api-gateway
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
    ports:
      - "8080:8080"
    networks:
      - microservice-network

  user-service:
    build:
      context: ./user-service
    image: elearn-user-service
    container_name: elearn-user-service
    env_file:
      - .env
    environment:
      SPRING_APPLICATION_NAME: user-service
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    ports:
      - "8081:8081"
    networks:
      - microservice-network

  backend-service:
    build:
      context: ./backend-service
    image: elearn-backend-service
    container_name: elearn-backend-service
    env_file:
      - .env
    environment:
      SPRING_APPLICATION_NAME: backend-service
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    ports:
      - "8082:8082"
    networks:
      - microservice-network

  ai-service:
    build:
      context: ./ai-service
    container_name: ai-service
    ports:
      - "8083:8083"
    environment:
      - OLLAMA_API_URL=http://ollama:11434/api/generate
      - BACKEND_API_URL=http://api-gateway:8080/api
    networks:
      - microservice-network
    depends_on:
      - backend-service
      - ollama
      - eureka-server

networks:
  microservice-network:
    driver: bridge
volumes:
  postgres_data:
  ollama_data: